name: device_monitor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
